public class StudentInfo2{
    public static void main(String []args){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Student john=new Student();
        Student s1=new Student("john","1533","Dhanmondi",3.4);
        Student s2=new Student("mike","1678","Gulshan",4.0);
        Student s3=new Student("carol","1788","Banani",2.7);
        
        String j=s1.getName()+","+s1.getID()+","+s1.getAddress()+","+s1.getCGPA();
        String m=s2.getName()+","+s2.getID()+","+s2.getAddress()+","+s2.getCGPA();
        String c=s3.getName()+","+s3.getID()+","+s3.getAddress()+","+s3.getCGPA();
        System.out.println(j);
        System.out.println(m);
        System.out.println(c);
    }
}
